### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by algebrait** [MisaZhu/KoalaJS#4]
var a;
var b;

for(var i=0; i<10000;i++) {
  a = "a";
  b = "b";
  // if do not ref each other, no leak
  a.x = b;
  b.x = a;
  if(i%1000==0) {
  // read from /proc/self/statm, second number is rss/4
  // RGlobal.mem();
  }
}

**Comment by algebrait** [comment]
seems leak not by ref cycle
if change
a.x = b;
b.x = a;
to
a.x = 1;
b.x = 2;
still leak.
I guess a and b do not leave the scope, so no chance to unref

**Comment by MisaZhu** [comment]
cool, will check it later, thanks:)

**Comment by algebrait** [comment]
a simple case
```javascript
var a;
for(var i=0; i<10000;i++) {
  a = 1;
  a.x = 1;
}
```

**Comment by algebrait** [comment]
evern this can not run?
```javascript
var a;
a.x=1;
print(a.x);
```

**Comment by algebrait** [comment]
got.
```javascript
var a;
```
init a as undefined
```javascript
a.x=1;
```
interp a.x as
```cpp
			case INSTR_GET: {
												str = bcode->getStr(offset);
												cout<<str<<"\n";
												StackItem* i = pop2();
												if(i != NULL) {
													BCVar* v = VAR(i);
													if(v->isString() || v->isObject() || v->isArray()) {
														doGet(v, str);
													}
													v->unref();
												}
												break;
											}
```
did not run doget

**Comment by MisaZhu** [comment]
fixed!

**Comment by algebrait** [comment]
What a tragedy!
```javascript
var a;
a.x = 1
```
is illegal in javascript.
so no problem at all.
